### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by xurich-xulaco** [OpusGang/adptvgrnMod#2]
```
Script evaluation failed:
Python exception: 'type' object is not subscriptable

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2819, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2820, in vapoursynth._vpy_evaluate
  File "P4CT017_ps2.py", line 6, in <module>
    from adptvgrnMod import *
  File "\Roaming\Python\Python38\site-packages\adptvgrnMod.py", line 10, in <module>
    strength: float | list[float] = 0.25,
TypeError: 'type' object is not subscriptable

pipe:: Invalid data found when processing input
```

Runned on Windows 10
Python version 3.8.10
Vapoursynth version 60

**Comment by quietvoid** [comment]
Minimum Python version is 3.9.
